const productState = [
  {
    id: "product1",
    title: "Nike Training Shorts",
    price: 35.0,
    imageUrl: "https://via.placeholder.com/300x200?text=Product+1",
    quantity: 0,
    added: false,
  },
  {
    id: "product2",
    title: "Adidas Running Shoes",
    price: 85.0,
    imageUrl: "https://via.placeholder.com/300x200?text=Product+2",
    quantity: 0,
    added: false,
  },
  {
    id: "product3",
    title: "Puma Sports T-Shirt",
    price: 25.0,
    imageUrl: "https://via.placeholder.com/300x200?text=Product+3",
    quantity: 0,
    added: false,
  },
  {
    id: "product4",
    title: "Under Armour Hoodie",
    price: 50.0,
    imageUrl: "https://via.placeholder.com/300x200?text=Product+4",
    quantity: 0,
    added: false,
  },
  {
    id: "product5",
    title: "Reebok Sports Cap",
    price: 20.0,
    imageUrl: "https://via.placeholder.com/300x200?text=Product+5",
    quantity: 0,
    added: false,
  },
  {
    id: "product6",
    title: "Nike Gym Bag",
    price: 60.0,
    imageUrl: "https://via.placeholder.com/300x200?text=Product+6",
    quantity: 0,
    added: false,
  },
  {
    id: "product7",
    title: "Adidas Yoga Mat",
    price: 40.0,
    imageUrl: "https://via.placeholder.com/300x200?text=Product+7",
    quantity: 0,
    added: false,
  },
  {
    id: "product8",
    title: "Puma Running Watch",
    price: 75.0,
    imageUrl: "https://via.placeholder.com/300x200?text=Product+8",
    quantity: 0,
    added: false,
  },
  {
    id: "product9",
    title: "Under Armour Sports Socks (Pack of 3)",
    price: 15.0,
    imageUrl: "https://via.placeholder.com/300x200?text=Product+9",
    quantity: 0,
    added: false,
  },
  {
    id: "product10",
    title: "Reebok Dumbbells Set",
    price: 45.0,
    imageUrl: "https://via.placeholder.com/300x200?text=Product+10",
    quantity: 0,
    added: false,
  },
  {
    id: "product11",
    title: "Nike Running Shorts",
    price: 40.0,
    imageUrl: "https://via.placeholder.com/300x200?text=Product+11",
    quantity: 0,
    added: false,
  },
  {
    id: "product12",
    title: "Adidas Performance Sneakers",
    price: 90.0,
    imageUrl: "https://via.placeholder.com/300x200?text=Product+12",
    quantity: 0,
    added: false,
  },
  {
    id: "product13",
    title: "Puma Sports Pants",
    price: 55.0,
    imageUrl: "https://via.placeholder.com/300x200?text=Product+13",
    quantity: 0,
    added: false,
  },
  {
    id: "product14",
    title: "Under Armour Running Shoes",
    price: 95.0,
    imageUrl: "https://via.placeholder.com/300x200?text=Product+14",
    quantity: 0,
    added: false,
  },
  {
    id: "product15",
    title: "Reebok Training Gloves",
    price: 25.0,
    imageUrl: "https://via.placeholder.com/300x200?text=Product+15",
    quantity: 0,
    added: false,
  },
  {
    id: "product16",
    title: "Nike Sports Water Bottle",
    price: 12.0,
    imageUrl: "https://via.placeholder.com/300x200?text=Product+16",
    quantity: 0,
    added: false,
  },
  {
    id: "product17",
    title: "Adidas Compression Leggings",
    price: 60.0,
    imageUrl: "https://via.placeholder.com/300x200?text=Product+17",
    quantity: 0,
    added: false,
  },
  {
    id: "product18",
    title: "Puma Soccer Ball",
    price: 30.0,
    imageUrl: "https://via.placeholder.com/300x200?text=Product+18",
    quantity: 0,
    added: false,
  },
  {
    id: "product19",
    title: "Under Armour Water-Resistant Jacket",
    price: 110.0,
    imageUrl: "https://via.placeholder.com/300x200?text=Product+19",
    quantity: 0,
    added: false,
  },
  {
    id: "product20",
    title: "Reebok Basketball Shoes",
    price: 120.0,
    imageUrl: "https://via.placeholder.com/300x200?text=Product+20",
    quantity: 0,
    added: false,
  }
];

export { productState };
